name: Build and publish nugets to server

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mv_nugets_matrix:
    strategy:
      matrix:
        libname: [MV, MV.Ide]

    build:
      runs-on: windows-latest

      steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Build MV
        run: dotnet publish libs/${{ matrix.libname }}
  
      - name: Send MV to NuGet
        uses: brandedoutcast/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: libs/${{ matrix.libname }}/${{ matrix.libname }}.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
      
