name: Build and publish nugets to server

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    #runs-on: ubuntu-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Publish LIB
      run: dotnet publish libs/MV
 
    - name: Lib to NuGet
      uses: brandedoutcast/publish-nuget@v2
      continue-on-error: true
      with:
        PROJECT_FILE_PATH: libs/MV/MV.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    
